import { GotchaPokemonCategory } from 'src/app/models/gotcha.model';

export const POKEMON_GOTCHA_V4: GotchaPokemonCategory[] = [
  {
    'title': '심볼 포켓몬 - 엔딩 이전',
    'data': [
      {
        'name': '베베놈',
        'level': 20,
        'location': '구름하수도',
        'requirement': '플라스마단과의 멀티배틀에서 승리',
        'note': '',
      },
      {
        'name': '비크티니',
        'level': 15,
        'location': '리버티가든섬',
        'requirement':
          '버그배지 획득 이전, 리버티가든섬의 등대 앞 베테랑 트레이너와의 배틀에서 승리',
        'note': '지나쳤을 경우 성신시티까지 진행해야 포획 가능',
      },
      {
        'name': '버랜지나',
        'level': 25,
        'location': '4번도로',
        'requirement': '',
        'note': '확정 이로치',
      },
      {
        'name': '디안시',
        'level': 40,
        'location': '고대샛길 PWT 방면',
        'requirement': '',
        'note': '',
      },
      {
        'name': '마기아나',
        'level': 40,
        'location': '고대의성 고대샛길 방면',
        'requirement': '',
        'note': '',
      },
      {
        'name': '볼케니온',
        'level': 50,
        'location': '리버스마운틴',
        'requirement': '난천에게 폭포오르기 비전머신 받기',
        'note': '',
      },
      {
        'name': '꿰뚫는화염',
        'level': 45,
        'location': '',
        'requirement': '',
        'note': '',
      },
      {
        'name': '날뛰는우레',
        'level': 45,
        'location': '전기돌동굴',
        'requirement': '',
        'note': '',
      },
      {
        'name': '굽이치는물결',
        'level': 45,
        'location': '궐수의동굴',
        'requirement': '',
        'note': '',
      },
      {
        'name': '탱탱겔',
        'level': 45,
        'location': '물결만',
        'requirement': '',
        'note': '확정 이로치',
      },
      {
        'name': '악식킹',
        'level': 50,
        'location': '쇼핑몰R9',
        'requirement': '',
        'note': '',
      },
      {
        'name': '코바르온',
        'level': 60,
        'location': '13번도로',
        'requirement': '',
        'note': '',
      },
      {
        'name': '비리디온',
        'level': 60,
        'location': '11번도로',
        'requirement': '',
        'note': '',
      },
      {
        'name': '테라키온',
        'level': 60,
        'location': '22번도로',
        'requirement': '웨이브배지를 획득한다.',
        'note': '',
      },
    ],
  },
  {
    'title': '심볼 포켓몬 - 엔딩 이후',
    'data': [
      {
        'name': '프리져',
        'level': 70,
        'location': '자이언트홀 입구',
        'requirement':
          '바람개비숲 방면 스카이애로 브리지 입구의 칠현인 스므라와 대화',
        'note': '',
      },
      {
        'name': '썬더',
        'level': 70,
        'location': '전기돌동굴',
        'requirement':
          '바람개비숲 방면 스카이애로 브리지 입구의 칠현인 스므라와 대화',
        'note': '',
      },
      {
        'name': '파이어',
        'level': 70,
        'location': '리버스마운틴 외부',
        'requirement':
          '바람개비숲 방면 스카이애로 브리지 입구의 칠현인 스므라와 대화',
        'note': '',
      },
      {
        'name': '뮤츠',
        'level': 85,
        'location': '지하수맥굴',
        'requirement':
          '지하수맥굴 지하로 내려가는 계단 앞 그린과의 배틀에서 승리',
        'note': '',
      },
      {
        'name': '뮤',
        'level': 70,
        'location': '머나먼고도',
        'requirement':
          '1. N에게 오래된해도를 받음\n2. 15번도로 시프트팩토리의 강연과 대화\n3. 모란만시티 항구 파일럿과 대화',
        'note': '',
      },
      {
        'name': '루기아',
        'level': 80,
        'location': '17번수로',
        'requirement':
          '1. 목호에게 은빛날개 받음\n2. 마름꽃마을 포켓몬 연구소의 주누운박사에게 성스러운분말 받음\n3. 칠보시티 카페 갤러지의 규리와 성스러운 분말을 교환',
        'note': '',
      },
      {
        'name': '칠색조',
        'level': 80,
        'location': '부채시티',
        'requirement':
          '1. 목호에게 은빛날개 받음\n2. 마름꽃마을 포켓몬 연구소의 주누운박사에게 성스러운분말 받음\n3. 칠보시티 카페 갤러지의 규리와 성스러운 분말을 교환',
        'note': '',
      },
      {
        'name': '세레비',
        'level': 70,
        'location': '하일링크의 숲',
        'requirement': '성신시티 주리의 집에서 민화와 대화',
        'note': 'C기어 > WIRELESS > 하일링크로 이동',
      },
      {
        'name': '레지락',
        'level': 65,
        'location': '땅밑유적 바위산의 방',
        'requirement': '야콘로드 땅밑유적의 베테랑 트레이너에게 열쇠 획득',
        'note': '',
      },
      {
        'name': '레지스틸',
        'level': 65,
        'location': '땅밑유적 쇠철의 방',
        'requirement': '야콘로드 땅밑유적의 베테랑 트레이너에게 열쇠 획득',
        'note': '하나링크 무쇠의 열쇠 필요',
      },
      {
        'name': '레지아이스',
        'level': 65,
        'location': '땅밑유적 빙산의 방',
        'requirement': '야콘로드 땅밑유적의 베테랑 트레이너에게 열쇠 획득',
        'note': '하나링크 빙산의 열쇠 필요',
      },
      {
        'name': '라티아스',
        'level': 75,
        'location': '15번도로',
        'requirement': '가륜마을 북쪽 절벽 이벤트 확인',
        'note': '',
      },
      {
        'name': '라티오스',
        'level': 75,
        'location': '18번도로',
        'requirement': '가륜마을 북쪽 절벽 이벤트 확인',
        'note': '',
      },
      {
        'name': '가이오가',
        'level': 85,
        'location': '해저유적',
        'requirement': '성신시티 체육관 관장들에게 승리 후 구슬 획득',
        'note': '',
      },
      {
        'name': '그란돈',
        'level': 85,
        'location': '리조트데저트',
        'requirement': '성신시티 체육관 관장들에게 승리 후 구슬 획득',
        'note': '',
      },
      {
        'name': '레쿠쟈',
        'level': 85,
        'location': '타워오브해븐',
        'requirement': '성신시티 체육관 관장들에게 승리 후 구슬 획득',
        'note': '종을 조사해야 출현',
      },
      {
        'name': '지라치',
        'level': 65,
        'location': '꿈터',
        'requirement': '',
        'note': '',
      },
      {
        'name': '테오키스',
        'level': 75,
        'location': '자이언트홀',
        'requirement': '칠보시티 박물관 운석 옆 NPC와 대화',
        'note': '',
      },
      {
        'name': '유크시',
        'level': 65,
        'location': '칠보시티',
        'requirement': '20번도로 마음의 공동에서 주박사와 이벤트 확인',
        'note': '',
      },
      {
        'name': '엠라이트',
        'level': 65,
        'location': '타워오브해븐',
        'requirement': '20번도로 마음의 공동에서 주박사와 이벤트 확인',
        'note': '',
      },
      {
        'name': '아그놈',
        'level': 65,
        'location': '23번도로',
        'requirement': '20번도로 마음의 공동에서 주박사와 이벤트 확인',
        'note': '',
      },
      {
        'name': '디아루가',
        'level': 85,
        'location': '길잡이의 공간',
        'requirement': '전당등록 후 유나이티드 타워에서 2회차 스토리 진행',
        'note': '',
      },
      {
        'name': '펄기아',
        'level': 85,
        'location': '18번도로',
        'requirement': '전당등록 후 유나이티드 타워에서 2회차 스토리 진행',
        'note': '',
      },
      {
        'name': '기라티나',
        'level': 85,
        'location': '유나이티드 타워',
        'requirement': '전당등록 후 유나이티드 타워에서 2회차 스토리 진행',
        'note': '',
      },
      {
        'name': '히드런',
        'level': 68,
        'location': '리버스마운틴',
        'requirement': '18번도로에서 화산의돌 획득',
        'note': '',
      },
      {
        'name': '레지기가스',
        'level': 68,
        'location': '태엽산',
        'requirement': '레지락, 레지아이스, 레지스틸을 파티에 소지',
        'note': '',
      },
      {
        'name': '크레세리아',
        'level': 68,
        'location': '원더브리지',
        'requirement': '스트레인저 하우스 이벤트 후 초승달날개 획득',
        'note': '',
      },
      {
        'name': '다크라이',
        'level': 75,
        'location': '스트레인저 하우스',
        'requirement': '크레세리아를 선두 배치',
        'note': '',
      },
      {
        'name': '쉐이미',
        'level': 70,
        'location': '사색의들판',
        'requirement': '바람개비숲 체렌 이벤트',
        'note': '성신시티 포켓몬센터의 유채로부터 그라데시아꽃 획득 가능',
      },
      {
        'name': '아르세우스',
        'level': 90,
        'location': '자연보호구역',
        'requirement': '2회차 스토리 완료 후 자연보호구역 방문',
        'note': '색이 다른 모습 고정',
      },
      {
        'name': '토네로스',
        'level': 70,
        'location': '설화의 습지초원',
        'requirement': '풍요의 사당 내부 사당 건축물 이벤트',
        'note': '',
      },
      {
        'name': '볼트로스',
        'level': 70,
        'location': '용나선탑 입구',
        'requirement': '풍요의 사당 내부 사당 건축물 이벤트',
        'note': '',
      },
      {
        'name': '제크로무',
        'level': 75,
        'location': '용나선탑',
        'requirement': 'N과의 배틀 승리 후 다크스톤 획득',
        'note': '',
      },
      {
        'name': '레시라무',
        'level': 75,
        'location': '용나선탑',
        'requirement':
          '1. 큐레무 소지\n2. 쌍용시티 배틀의 저택 내부의 할머니에게 라이트스톤 획득',
        'note': '',
      },
      {
        'name': '랜드로스',
        'level': 75,
        'location': '풍요의 사당',
        'requirement':
          '토네로스/볼트로스 포획 후 7번도로 민가의 할머니에게 확인',
        'note': '토네로스와 볼트로스 소지 필수',
      },
      {
        'name': '큐레무',
        'level': 70,
        'location': '자이언트홀',
        'requirement': '제크로무를 포획',
        'note': '',
      },
      {
        'name': '케르디오',
        'level': 75,
        'location': '맹세의 숲',
        'requirement':
          '1. 설화시티의 다크트리니티 승리 후 비전신약 획득\n2. 산가지마을 노간주의 집 뒷쪽의 불비달마에게 사용',
        'note': '',
      },
      {
        'name': '메로엣타',
        'level': 75,
        'location': '넝쿨마을',
        'requirement': '',
        'note':
          '메로엣타를 선두에 넣고 칠보시티 카페 갤러지 방문, 옛노래 습득 가능',
      },
      {
        'name': '게노세크트',
        'level': 75,
        'location': 'P2랩',
        'requirement': '',
        'note': '',
      },
    ],
  },
  {
    'title': '선물 포켓몬',
    'data': [
      {
        'name': '짜랑랑',
        'level': 5,
        'location': '산가지마을',
        'requirement': '',
        'note':
          '스타팅 포켓몬의 타입에 약한 타입의 포켓몬을 한 마리 받을 수 있음',
      },
      {
        'name': '태우지네',
        'level': 5,
        'location': '산가지마을',
        'requirement': '',
        'note':
          '스타팅 포켓몬의 타입에 약한 타입의 포켓몬을 한 마리 받을 수 있음',
      },
      {
        'name': '완철포',
        'level': 5,
        'location': '산가지마을',
        'requirement': '',
        'note':
          '스타팅 포켓몬의 타입에 약한 타입의 포켓몬을 한 마리 받을 수 있음',
      },
      {
        'name': '이상해씨',
        'level': 5,
        'location': '모란만시티',
        'requirement': '',
        'note': '1세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '파이리',
        'level': 5,
        'location': '모란만시티',
        'requirement': '',
        'note': '1세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '꼬부기',
        'level': 5,
        'location': '모란만시티',
        'requirement': '',
        'note': '1세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '알 (치고마)',
        'level': 1,
        'location': '모란만시티',
        'requirement': '철구와의 배틀에서 승리',
        'note': '',
      },
      {
        'name': '무쇠보따리',
        'level': 25,
        'location': '구름시티 (메달사무국 3층)',
        'requirement': '비틀배지',
        'note': '',
      },
      {
        'name': '나오하',
        'level': 5,
        'location': '구름시티\n(배틀컴퍼니 3층)',
        'requirement': '',
        'note': '9세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '뜨아거',
        'level': 5,
        'location': '구름시티\n(배틀컴퍼니 3층)',
        'requirement': '',
        'note': '9세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '꾸왁스',
        'level': 5,
        'location': '구름시티\n(배틀컴퍼니 3층)',
        'requirement': '',
        'note': '9세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '알 (가라르 화석)',
        'level': 1,
        'location': '구름시티 (배틀컴퍼니 3층)',
        'requirement': '배틀컴퍼니 사장과의 배틀에서 승리',
        'note': '파치래곤, 파치르돈, 어래곤, 어치르돈 중 무작위 부화',
      },
      {
        'name': '나몰빼미',
        'level': 5,
        'location': '가륜마을',
        'requirement': '',
        'note': '7세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '냐오불',
        'level': 5,
        'location': '가륜마을',
        'requirement': '',
        'note': '7세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '누리공',
        'level': 5,
        'location': '가륜마을',
        'requirement': '',
        'note': '7세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '도치마론',
        'level': 5,
        'location': '물풍경시티',
        'requirement': '',
        'note': '6세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '푸호꼬',
        'level': 5,
        'location': '물풍경시티',
        'requirement': '',
        'note': '6세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '개구마르',
        'level': 5,
        'location': '물풍경시티',
        'requirement': '',
        'note': '6세대 스타팅 중 한 마리를 선택',
      },
      {
        'name': '조로아(히스이)',
        'level': 30,
        'location': '물풍경시티',
        'requirement': 'N의 포켓몬 이벤트',
        'note': '',
      },
      {
        'name': '오거폰',
        'level': 40,
        'location': '6번도로 (날씨연구소)',
        'requirement': '계절에 따라 다른 폼 획득 (가면 교체 불가)',
        'note': '봄: 벽록, 여름: 우물, 가을: 화덕, 겨울: 주춧돌',
      },
      {
        'name': '알 (마나피)',
        'level': 1,
        'location': '3번도로 (게이트)',
        'requirement': '',
        'note': '',
      },
    ],
  },
  {
    'title': '교환 포켓몬',
    'data': [
      {
        'name': '님피아',
        'level': 0,
        'location': '4번도로 (민가)',
        'requirement': '이브이와 교환',
        'note': '전체 개체값 U(30), 성격: 온순',
      },
      {
        'name': '팽도리',
        'level': 0,
        'location': '7번도로 (민가)',
        'requirement': '클레피와 교환',
        'note': '공격 개체값 V(31), 성격: 고집, 특성: 단단한발톱',
      },
      {
        'name': '카르본',
        'level': 0,
        'location': '기하시티',
        'requirement': '대도각참과 교환',
        'note': '공격/특공 개체값 U(30), 성격: 노력, 특성: 의기양양',
      },
    ],
  },
];
